### ISSUE TITLE
Where is the 'CutNet' file?

### ISSUE THREAD

**Issue by strawberrieszd** [frazerlin/focuscut#6]
Thank you for such excellent work, there is a problem that bothers me, in main.py as shown below, I don't find CutNet and I want to ask where the file is to write this network。
![image](https://user-images.githubusercontent.com/107253962/201610319-a4f73401-ea37-4705-99c8-979cc9a711c8.png)

**Comment by frazerlin** [comment]
In main.py line 188 "exec('from model.{}.my_net import MyNet as CutNet'.
format(p['model']))", The MyNet in my_net.py is equal to the CutNet

strawberrieszd ***@***.***> 于2022年11月14日周一 16:22写道：
